### ISSUE TITLE
Curiosity questions

### ISSUE THREAD

**Issue by IrrenWirr** [open-spaced-repetition/cljc-fsrs#2]
Great work @vedang !
It is really nice to see a Clojure translation of the scheduler from @L-M-Sherlock (I'm sure one day we will also have the optimizer translated into Clojure 🔥)

I've had started a translation to Clojure a long while ago but procrastinated and never finished it.
But now, because of this I've got some curiosity questions about your implementation design/choices.

1.-

Is there more reasons in addition to ease of introspection/debug  (which is already a valid)  to store `:scheduled-days`  integers in the schedule ? 

like maybe it is used for the next step, for optimizing our weights ?
https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-mechanism-of-optimization

2.-

Have you thought of using a `next-interval` in hours/minutes instead of days ?

After all, the algorithm doesn't need to change except for removing the `Math/round` and multiplying by `24(h)` or `24(h)*60(m)`

Did you kept it that way to have a more homogeneous/faithful translation ? to reduce the need of more code (wouldn't `...card/new-repetition-elapsed-days` already be enough for that ? ) and/or reduce computation run-cost at the application side ? another reason ?

**Comment by L-M-Sherlock** [comment]
> Is there more reasons in addition to ease of introspection/debug (which is already a valid) to store `:scheduled-days` integers in the schedule ?

It's optional. Anki stored `ivl` in its database. In the optimization, we don't need it.

**Comment by vedang** [comment]
I didn't see a use-case for keeping the `next-interval` in a value less than days, since it looked like the algorithm would never produce such a value. The first question has already been answered above.

Thank you so much for your praise :D I was not sure if anyone would be interested in the Clojure version, but I'm implementing something that uses FSRS so this library is directly useful to me (and hence I'll keep on maintaining it for the foreseeable future)
