### ISSUE TITLE
bug with rating indexes ?

### ISSUE THREAD

**Issue by IrrenWirr** [open-spaced-repetition/cljc-fsrs#3]
I think there are bugs with ratings.

Given that the original
https://github.com/open-spaced-repetition/fsrs4anki/blob/884741bc9f804ff428540184e0c971875f128fd1/fsrs4anki_scheduler.js#L103
where the rating of fsrs4anki_scheduler.js : `{:again 1, :hard  2, :good  3, :easy  4}` but the Clojure one is : `{:again 0, :hard  1, :good  2, :easy  3}` (which I must say, I prefer, it seems cleaner to have :again at 0).

Is there a bug in the Clojure's `init-difficulty` algorithm ? where it should subtract only `2` instead of `3` ?

Because `init-stability` in the Clojure code-base don't subtract `-1`  like the js-anki version (which seems valid because the ratings start at `0` in Clojure code-base).
https://github.com/open-spaced-repetition/fsrs4anki/blob/884741bc9f804ff428540184e0c971875f128fd1/fsrs4anki_scheduler.js#L228

The same case applies to the `next-difficulty` fn.

**Comment by vedang** [comment]
Hi @IrrenWirr , 

There wasn't a bug in the code. The ratings were adjusted to `0`, `1` ... because they also existed at those indices in the `default-weights` for the `fsrs4anki` implementation. So I decided to maintain the data in a single place and changed the code to be lookups in the default-weights array instead of the direct weight of a rating.

However, @L-M-Sherlock has said that the Go implementation should be considered canonical -- #4 and my own changes on top of it closely mirror the Go code now. I will close this issue as soon as I push the changes to upstream.

Thanks!
